/**
 * Pure ffmpeg filter-graph / argument builders for the B-Roll export.
 *
 * Everything in this module is side-effect free and DOM free: it turns the
 * B-Roll store data (clips, backgrounds, overlays, transitions) into ffmpeg
 * command lines. `brollCompositor.ts` feeds the results to ffmpeg.wasm.
 *
 * Keeping the string building here means the whole graph can be built (and
 * asserted on) without a browser - see `scripts/check-broll-filtergraph.mjs`.
 */
import type { BRollClip, ClipBackground, ClipOverlay, TransitionType } from '../../store/brollStore';
import { IMAGE_BASE_WIDTH, getOverlayRange } from '../Editor/BRoll/Overlays/overlayRender';

/* -------------------------------------------------------------------------- */
/*  Transitions                                                               */
/* -------------------------------------------------------------------------- */

/**
 * How the editor's transitions are baked with ffmpeg's `xfade` filter.
 *
 * | store type    | xfade      | why                                          |
 * | ------------- | ---------- | -------------------------------------------- |
 * | `fade`        | fade       | straight cross fade                           |
 * | `dissolve`    | dissolve   | noise-driven dissolve, matches the preview    |
 * | `slide-left`  | slideleft  | 1:1                                           |
 * | `slide-right` | slideright | 1:1                                           |
 * | `slide-up`    | slideup    | 1:1                                           |
 * | `slide-down`  | slidedown  | 1:1                                           |
 * | `wipe`        | wipeleft   | the preview wipes left→right revealing the new clip |
 * | `cross-zoom`  | zoomin     | closest zoom based transition xfade ships     |
 * | `rotate`      | radial     | xfade has no rotation; `radial` is the only sweep that rotates around the centre |
 */
export const TRANSITION_TO_XFADE: Record<TransitionType, string> = {
  fade: 'fade',
  dissolve: 'dissolve',
  'slide-left': 'slideleft',
  'slide-right': 'slideright',
  'slide-up': 'slideup',
  'slide-down': 'slidedown',
  wipe: 'wipeleft',
  'cross-zoom': 'zoomin',
  rotate: 'radial'
};

/** xfade refuses zero length transitions. */
export const MIN_TRANSITION_DURATION = 0.1;
/** A transition may never eat more than this share of either neighbour. */
const MAX_TRANSITION_SHARE = 0.9;

export const xfadeTransition = (type: TransitionType | undefined): string =>
  (type && TRANSITION_TO_XFADE[type]) || TRANSITION_TO_XFADE.fade;

/* -------------------------------------------------------------------------- */
/*  Formatting helpers                                                        */
/* -------------------------------------------------------------------------- */

const clamp = (value: number, min: number, max: number, fallback = min): number => {
  if (!Number.isFinite(value)) return fallback;
  return Math.min(max, Math.max(min, value));
};

const clamp01 = (value: number): number => clamp(value, 0, 1, 0);

/** Compact, locale independent number for a filter argument. */
export const num = (value: number, decimals = 3): string => {
  if (!Number.isFinite(value)) return '0';
  const factor = 10 ** decimals;
  return String(Math.round(value * factor) / factor);
};

const evenPixels = (value: number, fallback: number): number => {
  const rounded = Math.round(Number.isFinite(value) && value > 0 ? value : fallback);
  const clamped = Math.min(3840, Math.max(16, rounded));
  return clamped % 2 === 0 ? clamped : clamped - 1;
};

/**
 * Quotes for the filter-graph parser. Quotes/backslashes are dropped rather
 * than escaped: no value we build legitimately contains them, and dropping is
 * the only way to guarantee the graph cannot be broken out of.
 */
export const quoteFilterValue = (value: string): string => `'${value.replace(/['\\]/g, '')}'`;

/** MEMFS names are generated by us, this only guards against odd clip names. */
export const safeFileName = (value: string): string => value.replace(/[^a-zA-Z0-9._-]/g, '_');

/** `#rgb` / `#rrggbb` / `0xrrggbb` → the `0xRRGGBB` form ffmpeg understands. */
export const toFFmpegColor = (value: string | null | undefined, fallback = '0x000000'): string => {
  if (!value) return fallback;
  const raw = value.trim().replace(/^#/, '').replace(/^0x/i, '');
  if (/^[0-9a-f]{3}$/i.test(raw)) {
    const [r, g, b] = raw.split('');
    return `0x${r}${r}${g}${g}${b}${b}`.toUpperCase().replace('0X', '0x');
  }
  if (/^[0-9a-f]{6}$/i.test(raw)) return `0x${raw.toUpperCase()}`;
  if (/^[0-9a-f]{8}$/i.test(raw)) return `0x${raw.slice(0, 6).toUpperCase()}`;
  return fallback;
};

const withAlpha = (color: string, alpha: number): string => `${color}@${num(clamp01(alpha))}`;

/* -------------------------------------------------------------------------- */
/*  Overlay helpers                                                           */
/* -------------------------------------------------------------------------- */

/** Font size in output pixels, mirroring `overlayRender.drawOverlay`. */
export const overlayFontSize = (overlay: ClipOverlay, height: number): number =>
  Math.max(4, Math.round((overlay.fontSize / 100) * height * Math.max(0.05, overlay.scale)));

/** On-screen width of an image overlay, mirroring `overlayRender.drawOverlay`. */
export const overlayImageWidth = (overlay: ClipOverlay, width: number): number =>
  Math.max(2, Math.round(width * IMAGE_BASE_WIDTH * Math.max(0.05, overlay.scale)));

/** Bounding box of a rotated rectangle (ffmpeg's `rotate` grows the frame). */
export const rotatedSize = (
  width: number,
  height: number,
  degrees: number
): { width: number; height: number } => {
  const radians = (degrees * Math.PI) / 180;
  const cos = Math.abs(Math.cos(radians));
  const sin = Math.abs(Math.sin(radians));
  return {
    width: Math.max(2, Math.round(width * cos + height * sin)),
    height: Math.max(2, Math.round(height * cos + width * sin))
  };
};

/**
 * Alpha of an overlay as an ffmpeg expression of `t` (seconds into the clip).
 * Mirrors `overlayRender.getOverlayAlpha`: opacity with linear fade in/out.
 */
export const buildOverlayAlphaExpression = (overlay: ClipOverlay): string => {
  const { start, end } = getOverlayRange(overlay);
  const span = Math.max(0, end - start);
  const fade = Math.max(0, Math.min(overlay.fadeDuration, span / 2));
  const opacity = clamp01(overlay.opacity);

  if (fade <= 0 || span <= 0) return num(opacity);

  const fadeIn = `${num(opacity)}*(t-${num(start)})/${num(fade)}`;
  const fadeOut = `${num(opacity)}*(${num(end)}-t)/${num(fade)}`;
  return (
    `if(lt(t,${num(start)}),0,` +
    `if(lt(t,${num(start + fade)}),${fadeIn},` +
    `if(lt(t,${num(end - fade)}),${num(opacity)},` +
    `if(lt(t,${num(end)}),${fadeOut},0))))`
  );
};

/** `enable=` window for an overlay. */
export const buildOverlayEnableExpression = (overlay: ClipOverlay): string => {
  const { start, end } = getOverlayRange(overlay);
  return `between(t,${num(start)},${num(end)})`;
};

/* -------------------------------------------------------------------------- */
/*  Clip pass                                                                 */
/* -------------------------------------------------------------------------- */

export interface TextOverlayRender {
  kind: 'text';
  overlay: ClipOverlay;
  /** MEMFS path holding the text (keeps user text out of the filter graph). */
  textFile: string;
  /** MEMFS path of the TrueType font drawtext renders with. */
  fontFile: string;
}

export interface ImageOverlayRender {
  kind: 'image';
  overlay: ClipOverlay;
  /** MEMFS path of the decoded overlay image. */
  file: string;
  /** Natural pixel size of the image, used to keep its aspect ratio. */
  naturalWidth: number;
  naturalHeight: number;
}

export type OverlayRender = TextOverlayRender | ImageOverlayRender;

export interface BRollClipPassRequest {
  /** Output frame size - identical for every clip so xfade can chain them. */
  width: number;
  height: number;
  fps: number;
  /** How long this clip lasts inside the sequence, in seconds. */
  duration: number;
  source: {
    file: string;
    /** Images are looped for `duration` seconds instead of decoded as video. */
    still: boolean;
    /** Seconds skipped at the head of the source. */
    trimStart?: number;
    /** The source carries an audio stream we should keep. */
    hasAudio?: boolean;
  };
  background?: ClipBackground | null;
  /** MEMFS path of the background image (only used when mode === 'image'). */
  backgroundFile?: string | null;
  overlays?: OverlayRender[];
  colorFilters?: BRollClip['filters'];
  volume?: number;
  /** Fade in from black/silence at the head of the clip, in seconds. */
  fadeIn?: number;
  output: string;
  /** x264 CRF for the intermediate file. */
  crf?: number;
  preset?: string;
}

/** Image fit chain shared by background images. */
const imageFitChain = (fit: ClipBackground['imageFit'], width: number, height: number): string => {
  switch (fit) {
    case 'contain':
      return (
        `scale=${width}:${height}:force_original_aspect_ratio=decrease,` +
        `pad=${width}:${height}:(ow-iw)/2:(oh-ih)/2:color=black`
      );
    case 'stretch':
      return `scale=${width}:${height}`;
    case 'cover':
    default:
      return `scale=${width}:${height}:force_original_aspect_ratio=increase,crop=${width}:${height}`;
  }
};

interface InputArgs {
  args: string[];
  /** ffmpeg input index of every declared input. */
  sourceIndex: number;
  backgroundIndex: number | null;
  overlayIndexes: number[];
  silenceIndex: number;
}

const buildInputArgs = (request: BRollClipPassRequest): InputArgs => {
  const args: string[] = [];
  const duration = Math.max(0.05, request.duration);
  const fps = clamp(request.fps, 1, 120, 30);
  let index = 0;

  // 0: the clip itself.
  if (request.source.still) {
    args.push('-loop', '1', '-framerate', num(fps), '-t', num(duration), '-i', request.source.file);
  } else {
    const trimStart = Math.max(0, request.source.trimStart ?? 0);
    if (trimStart > 0) args.push('-ss', num(trimStart));
    args.push('-t', num(duration), '-i', request.source.file);
  }
  const sourceIndex = index;
  index += 1;

  // 1: background image (still, looped so it lasts the whole clip).
  let backgroundIndex: number | null = null;
  if (request.background?.mode === 'image' && request.backgroundFile) {
    args.push('-loop', '1', '-framerate', num(fps), '-t', num(duration), '-i', request.backgroundFile);
    backgroundIndex = index;
    index += 1;
  }

  // 2..n: overlay images (looped so `fade` can animate their alpha over time).
  const overlayIndexes: number[] = [];
  for (const overlay of request.overlays ?? []) {
    if (overlay.kind !== 'image') {
      overlayIndexes.push(-1);
      continue;
    }
    args.push('-loop', '1', '-framerate', num(fps), '-t', num(duration), '-i', overlay.file);
    overlayIndexes.push(index);
    index += 1;
  }

  // last: silence, used whenever the clip has no audio of its own so every
  // normalised clip can be joined with `acrossfade`.
  args.push(
    '-f',
    'lavfi',
    '-t',
    num(duration),
    '-i',
    'anullsrc=channel_layout=stereo:sample_rate=44100'
  );
  const silenceIndex = index;

  return { args, sourceIndex, backgroundIndex, overlayIndexes, silenceIndex };
};

/**
 * Background compositing.
 *
 * IMPORTANT LIMITATION: ffmpeg.wasm cannot run person segmentation, so the
 * background is *not* replaced around a segmented subject the way the live
 * preview does. Instead the chosen colour / blur plate / image is rendered as a
 * full-frame backdrop and the clip is fitted on top of it, so it shows wherever
 * the clip does not cover the frame (letterbox / pillarbox areas).
 */
const buildBackgroundChain = (
  request: BRollClipPassRequest,
  inputs: InputArgs
): { chains: string[]; label: string } => {
  const width = evenPixels(request.width, 1280);
  const height = evenPixels(request.height, 720);
  const fps = clamp(request.fps, 1, 120, 30);
  const duration = Math.max(0.05, request.duration);
  const fit = `scale=${width}:${height}:force_original_aspect_ratio=decrease,setsar=1`;
  const source = `[${inputs.sourceIndex}:v]`;
  const mode = request.background?.mode ?? 'none';
  const chains: string[] = [];

  if (mode === 'color') {
    const color = toFFmpegColor(request.background?.color, '0x000000');
    chains.push(`color=c=${color}:s=${width}x${height}:r=${num(fps)}:d=${num(duration)},setsar=1[bgplate]`);
    chains.push(`${source}fps=${fps},${fit}[bgfg]`);
    chains.push('[bgplate][bgfg]overlay=(W-w)/2:(H-h)/2:shortest=1[bgout]');
    return { chains, label: '[bgout]' };
  }

  if (mode === 'blur') {
    // Radius has to stay well inside the frame or boxblur refuses to run.
    const maxRadius = Math.max(1, Math.floor(Math.min(width, height) / 2) - 1);
    const radius = Math.round(clamp(request.background?.blurAmount ?? 12, 1, maxRadius, 12));
    chains.push(`${source}fps=${fps},split=2[bgsrc][fgsrc]`);
    chains.push(
      `[bgsrc]scale=${width}:${height}:force_original_aspect_ratio=increase,crop=${width}:${height},` +
        `boxblur=luma_radius=${radius}:luma_power=2:chroma_radius=${radius}:chroma_power=2,setsar=1[bgplate]`
    );
    chains.push(`[fgsrc]${fit}[bgfg]`);
    chains.push('[bgplate][bgfg]overlay=(W-w)/2:(H-h)/2:shortest=1[bgout]');
    return { chains, label: '[bgout]' };
  }

  if (mode === 'image' && inputs.backgroundIndex !== null) {
    const fitChain = imageFitChain(request.background?.imageFit ?? 'cover', width, height);
    chains.push(`[${inputs.backgroundIndex}:v]fps=${fps},${fitChain},setsar=1[bgplate]`);
    chains.push(`${source}fps=${fps},${fit}[bgfg]`);
    chains.push('[bgplate][bgfg]overlay=(W-w)/2:(H-h)/2:shortest=1[bgout]');
    return { chains, label: '[bgout]' };
  }

  // 'none' (and 'image' without a usable picture): plain letterbox on black.
  chains.push(
    `${source}fps=${fps},${fit},pad=${width}:${height}:(ow-iw)/2:(oh-ih)/2:color=black[bgout]`
  );
  return { chains, label: '[bgout]' };
};

const buildColorFilterChain = (filters: BRollClip['filters'] | undefined): string[] => {
  if (!filters) return [];
  const parts: string[] = [];
  const brightness = clamp(filters.brightness ?? 1, 0, 3, 1) - 1;
  const contrast = clamp(filters.contrast ?? 1, 0, 3, 1);
  const saturation = clamp(filters.saturation ?? 1, 0, 3, 1);

  if (Math.abs(brightness) > 0.001 || Math.abs(contrast - 1) > 0.001 || Math.abs(saturation - 1) > 0.001) {
    parts.push(
      `eq=brightness=${num(clamp(brightness, -1, 1, 0))}:contrast=${num(contrast)}:saturation=${num(saturation)}`
    );
  }

  const blur = clamp(filters.blur ?? 0, 0, 50, 0);
  if (blur >= 1) {
    const radius = Math.round(blur);
    parts.push(`boxblur=luma_radius=${radius}:luma_power=1:chroma_radius=${radius}:chroma_power=1`);
  }

  return parts;
};

const buildTextOverlayFilter = (
  render: TextOverlayRender,
  width: number,
  height: number
): string => {
  const { overlay } = render;
  const fontSize = overlayFontSize(overlay, height);
  const centerX = Math.round(clamp01(overlay.position.x) * width);
  const centerY = Math.round(clamp01(overlay.position.y) * height);

  const options = [
    `fontfile=${quoteFilterValue(render.fontFile)}`,
    `textfile=${quoteFilterValue(render.textFile)}`,
    'reload=0',
    `fontsize=${fontSize}`,
    `fontcolor=${toFFmpegColor(overlay.color, '0xFFFFFF')}`,
    `x=${quoteFilterValue(`${centerX}-text_w/2`)}`,
    `y=${quoteFilterValue(`${centerY}-text_h/2`)}`,
    `line_spacing=${Math.round(fontSize * 0.15)}`,
    `alpha=${quoteFilterValue(buildOverlayAlphaExpression(overlay))}`,
    `enable=${quoteFilterValue(buildOverlayEnableExpression(overlay))}`
  ];

  if (overlay.backgroundColor) {
    options.push(
      'box=1',
      `boxcolor=${toFFmpegColor(overlay.backgroundColor, '0x000000')}`,
      `boxborderw=${Math.max(1, Math.round(fontSize * 0.35))}`
    );
  }

  if (overlay.fontWeight === 'bold') {
    // Only the regular weight is bundled, so bold is faked with a border in the
    // text colour - visually very close to a real bold face at overlay sizes.
    options.push(
      `borderw=${Math.max(1, Math.round(fontSize * 0.035))}`,
      `bordercolor=${toFFmpegColor(overlay.color, '0xFFFFFF')}`
    );
  }

  if (overlay.shadow) {
    options.push(
      `shadowcolor=${withAlpha('0x000000', 0.6)}`,
      `shadowx=${Math.max(1, Math.round(fontSize * 0.04))}`,
      `shadowy=${Math.max(1, Math.round(fontSize * 0.06))}`
    );
  }

  return `drawtext=${options.join(':')}`;
};

const buildImageOverlayChain = (
  render: ImageOverlayRender,
  inputIndex: number,
  label: string,
  width: number,
  height: number
): { chain: string; x: number; y: number } => {
  const { overlay } = render;
  const drawWidth = overlayImageWidth(overlay, width);
  const ratio =
    render.naturalWidth > 0 && render.naturalHeight > 0
      ? render.naturalHeight / render.naturalWidth
      : 9 / 16;
  const drawHeight = Math.max(2, Math.round(drawWidth * ratio));

  const parts = [`scale=${drawWidth}:${drawHeight}`, 'format=rgba'];

  const rotation = Number.isFinite(overlay.rotation) ? overlay.rotation : 0;
  let boxWidth = drawWidth;
  let boxHeight = drawHeight;
  if (Math.abs(rotation) > 0.01) {
    const box = rotatedSize(drawWidth, drawHeight, rotation);
    boxWidth = box.width;
    boxHeight = box.height;
    // ffmpeg rotates clockwise for positive angles, same as the canvas preview.
    parts.push(
      `rotate=${num((rotation * Math.PI) / 180, 5)}:c=none:ow=${boxWidth}:oh=${boxHeight}`
    );
  }

  const { start, end } = getOverlayRange(overlay);
  const span = Math.max(0, end - start);
  const fade = Math.max(0, Math.min(overlay.fadeDuration, span / 2));
  parts.push(`colorchannelmixer=aa=${num(clamp01(overlay.opacity))}`);
  if (fade > 0) {
    parts.push(`fade=t=in:st=${num(start)}:d=${num(fade)}:alpha=1`);
    parts.push(`fade=t=out:st=${num(end - fade)}:d=${num(fade)}:alpha=1`);
  }

  return {
    chain: `[${inputIndex}:v]${parts.join(',')}${label}`,
    x: Math.round(clamp01(overlay.position.x) * width - boxWidth / 2),
    y: Math.round(clamp01(overlay.position.y) * height - boxHeight / 2)
  };
};

/**
 * Builds the complete ffmpeg command that renders ONE clip with its background
 * and overlays baked in, normalised to the sequence's frame size / fps and with
 * a guaranteed stereo audio track.
 */
export const buildClipPassArgs = (request: BRollClipPassRequest): string[] => {
  const width = evenPixels(request.width, 1280);
  const height = evenPixels(request.height, 720);
  const duration = Math.max(0.05, request.duration);
  const inputs = buildInputArgs(request);

  const chains: string[] = [];
  const background = buildBackgroundChain(request, inputs);
  chains.push(...background.chains);

  let videoLabel = background.label;
  let step = 0;

  const colorFilters = buildColorFilterChain(request.colorFilters);
  if (colorFilters.length > 0) {
    step += 1;
    const next = `[cf${step}]`;
    chains.push(`${videoLabel}${colorFilters.join(',')}${next}`);
    videoLabel = next;
  }

  (request.overlays ?? []).forEach((overlay, index) => {
    if (!overlay.overlay.visible) return;
    step += 1;

    if (overlay.kind === 'text') {
      const next = `[ov${step}]`;
      chains.push(`${videoLabel}${buildTextOverlayFilter(overlay, width, height)}${next}`);
      videoLabel = next;
      return;
    }

    const inputIndex = inputs.overlayIndexes[index];
    if (inputIndex === undefined || inputIndex < 0) return;

    const layer = `[ovsrc${step}]`;
    const next = `[ov${step}]`;
    const built = buildImageOverlayChain(overlay, inputIndex, layer, width, height);
    chains.push(built.chain);
    chains.push(
      `${videoLabel}${layer}overlay=${built.x}:${built.y}:` +
        `enable=${quoteFilterValue(buildOverlayEnableExpression(overlay.overlay))}${next}`
    );
    videoLabel = next;
  });

  const fadeIn = clamp(request.fadeIn ?? 0, 0, Math.max(0, duration / 2), 0);
  const tail = ['format=yuv420p'];
  if (fadeIn > 0) tail.unshift(`fade=t=in:st=0:d=${num(fadeIn)}`);
  chains.push(`${videoLabel}${tail.join(',')}[vout]`);

  // Audio: the clip's own track when it has one, silence otherwise.
  const audioSource = request.source.hasAudio ? `[${inputs.sourceIndex}:a]` : `[${inputs.silenceIndex}:a]`;
  const audioParts = ['aformat=sample_fmts=fltp:sample_rates=44100:channel_layouts=stereo'];
  const volume = clamp(request.volume ?? 1, 0, 4, 1);
  if (Math.abs(volume - 1) > 0.001) audioParts.push(`volume=${num(volume)}`);
  if (fadeIn > 0) audioParts.push(`afade=t=in:st=0:d=${num(fadeIn)}`);
  chains.push(`${audioSource}${audioParts.join(',')}[aout]`);

  const crf = Math.round(clamp(request.crf ?? 20, 0, 51, 20));
  const preset = request.preset ?? 'veryfast';

  return [
    '-nostdin',
    ...inputs.args,
    '-filter_complex',
    chains.join(';'),
    '-map',
    '[vout]',
    '-map',
    '[aout]',
    '-t',
    num(duration),
    '-c:v',
    'libx264',
    '-preset',
    preset,
    '-crf',
    String(crf),
    '-pix_fmt',
    'yuv420p',
    '-c:a',
    'aac',
    '-b:a',
    '192k',
    '-ar',
    '44100',
    '-ac',
    '2',
    request.output
  ];
};

/* -------------------------------------------------------------------------- */
/*  Timeline pass                                                             */
/* -------------------------------------------------------------------------- */

export interface TimelineSegment {
  /** MEMFS path of the normalised clip produced by `buildClipPassArgs`. */
  file: string;
  duration: number;
  /** How this segment enters from the previous one. `null` = hard cut. */
  transition?: { type: TransitionType; duration: number } | null;
}

export interface TimelineTransitionPlan {
  /** Index of the incoming segment. */
  index: number;
  xfade: string;
  duration: number;
  offset: number;
}

export interface TimelinePlan {
  transitions: TimelineTransitionPlan[];
  totalDuration: number;
}

/**
 * Works out the xfade offsets. Each transition overlaps the two neighbouring
 * clips, so the timeline shortens by the transition duration every time.
 */
export const planTimeline = (segments: TimelineSegment[]): TimelinePlan => {
  const transitions: TimelineTransitionPlan[] = [];
  if (segments.length === 0) return { transitions, totalDuration: 0 };

  let total = Math.max(0.05, segments[0].duration);

  for (let index = 1; index < segments.length; index += 1) {
    const segment = segments[index];
    const segmentDuration = Math.max(0.05, segment.duration);
    const requested = segment.transition?.duration ?? 0;

    const maxDuration = Math.min(total, segmentDuration) * MAX_TRANSITION_SHARE;
    const duration = segment.transition
      ? clamp(requested, MIN_TRANSITION_DURATION, Math.max(MIN_TRANSITION_DURATION, maxDuration), MIN_TRANSITION_DURATION)
      : 0;

    if (duration > 0) {
      transitions.push({
        index,
        xfade: xfadeTransition(segment.transition?.type),
        duration,
        offset: Math.max(0, total - duration)
      });
    }

    total = total + segmentDuration - duration;
  }

  return { transitions, totalDuration: total };
};

export interface TimelinePassOptions {
  output: string;
  crf?: number;
  preset?: string;
  audioBitrate?: number;
  fastStart?: boolean;
}

export interface TimelinePass {
  args: string[];
  totalDuration: number;
}

/**
 * Joins the normalised clips into the final video, cross fading video with
 * `xfade` and audio with `acrossfade` so both stay in sync.
 */
export const buildTimelinePassArgs = (
  segments: TimelineSegment[],
  options: TimelinePassOptions
): TimelinePass => {
  if (segments.length < 2) {
    throw new Error('The timeline pass needs at least two clips.');
  }

  const plan = planTimeline(segments);
  const byIndex = new Map(plan.transitions.map((transition) => [transition.index, transition]));

  const chains: string[] = [];
  let videoLabel = '[0:v]';
  let audioLabel = '[0:a]';

  for (let index = 1; index < segments.length; index += 1) {
    const transition = byIndex.get(index);
    const nextVideo = `[vx${index}]`;
    const nextAudio = `[ax${index}]`;

    if (transition) {
      chains.push(
        `${videoLabel}[${index}:v]xfade=transition=${transition.xfade}:` +
          `duration=${num(transition.duration)}:offset=${num(transition.offset)}${nextVideo}`
      );
      chains.push(
        `${audioLabel}[${index}:a]acrossfade=d=${num(transition.duration)}:c1=tri:c2=tri${nextAudio}`
      );
    } else {
      // Hard cut: concat keeps the same labelling so the chain stays uniform.
      chains.push(
        `${videoLabel}${audioLabel}[${index}:v][${index}:a]concat=n=2:v=1:a=1${nextVideo}${nextAudio}`
      );
    }

    videoLabel = nextVideo;
    audioLabel = nextAudio;
  }

  const inputs = segments.flatMap((segment) => ['-i', segment.file]);
  const crf = Math.round(clamp(options.crf ?? 20, 0, 51, 20));
  const audioBitrate = Math.round(clamp(options.audioBitrate ?? 192, 32, 512, 192));

  const args = [
    '-nostdin',
    ...inputs,
    '-filter_complex',
    chains.join(';'),
    '-map',
    videoLabel,
    '-map',
    audioLabel,
    '-c:v',
    'libx264',
    '-preset',
    options.preset ?? 'veryfast',
    '-crf',
    String(crf),
    '-pix_fmt',
    'yuv420p',
    '-c:a',
    'aac',
    '-b:a',
    `${audioBitrate}k`,
    '-ar',
    '44100',
    '-ac',
    '2'
  ];

  if (options.fastStart !== false) args.push('-movflags', '+faststart');
  args.push(options.output);

  return { args, totalDuration: plan.totalDuration };
};

/** Probe used to find out whether a source really carries an audio stream. */
export const buildAudioProbeArgs = (file: string): string[] => [
  '-nostdin',
  '-hide_banner',
  '-i',
  file,
  '-map',
  '0:a:0',
  '-t',
  '0.05',
  '-f',
  'null',
  '-'
];
